name: hoppy
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  go_router: ^12.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  firebase_core: ^2.21.0
  cloud_firestore: ^4.12.2
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/backgrounds/
    - assets/images/beers/
    - assets/images/countries/
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy.ttf
    - family: Gobold
      fonts:
        - asset: assets/fonts/gobold.otf
