const kMaxFavorite = 20;
const kDefaultPadding = 20.0;
const kDefaultRadius = 10.0;
const kFooterButtonHeight = 60.0;
const kCardHeight = 420.0;
const kCardVerticalMargin = 2.0;
const kChartArcWidth = 70;
const kInfiniteScrollDifference = 200.0;
const kBeerCardAspectRatio = 4 / 7;
